name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          fingerprint: ${{ secrets.DEPLOY_HOST_FINGERPRINT }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          script: ./deploy.sh

